### ISSUE TITLE
[HOLD] Improve repo setup

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/react-native-x-maps#14]
Collaborate with an expert agency to setup `react-native-x-maps` as a rigorous open-source project.

**Comment by hayata-suenaga** [comment]
Engineers at SWM are on vacation during August.

Can start working on this with them on [August 28 when they come back.](https://expensify.slack.com/archives/C04878MDF34/p1691077181596209?thread_ts=1690588437.436969&cid=C04878MDF34)

**Comment by kacperkapusciak** [comment]
Hey! 👋 

I’m Kacper Kapuściak from Software Mansion, an expert agency, and I’d like to work on this issue

**Comment by hayata-suenaga** [comment]
@kacperkapusciak could you actually hold the work for now a little bit? We have an internal discussion related to this task, and it might affect if we gonna carry out polishing the setup or not 🙇

**Comment by neil-marcellini** [comment]
Updating title to HOLD for [this discussion](https://expensify.slack.com/archives/C03TQ48KC/p1693240753590539)

**Comment by kacperkapusciak** [comment]
@hayata-suenaga sure!

**Comment by hayata-suenaga** [comment]
@kacperkapusciak I apologize but we decided not to move forward with this plan 🙇 Closing this issue now
