### ISSUE TITLE
Setup TypeScript for react-native-x-maps

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/react-native-x-maps#7]
- [x] Init `tsconfig.json`
- [x] Install and configure TypeScript ESLint plugins
- [x] Setup CL for type checking

**Comment by neil-marcellini** [comment]
I'm re-opening this because it [sounds like](https://github.com/Expensify/react-native-x-maps/pull/10#issuecomment-1663063956) there needs to be a little clean up PR.

**Comment by hayata-suenaga** [comment]
thank you for reopening. Linking the cleanup issue here #12

**Comment by hayata-suenaga** [comment]
Moving this to CRITICAL as this is required to implement Map

**Comment by hayata-suenaga** [comment]
The fix for the build failure has been merged
